$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
endpoint_name: bike-sharing-ep
code_configuration:
  code: .
  scoring_script: score.py
environment:
  conda_file: conda_endpoint.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
instance_type: Standard_DS1_v2
instance_count: 1
environment_variables:
  MLFLOW_TRACKING_URI: azureml://australiaeast.api.azureml.ms/mlflow/v1.0/subscriptions/c1e35fa8-f310-4b3d-b316-7a220c06c672/resourceGroups/rg-bike-sharing/providers/Microsoft.MachineLearningServices/workspaces/mlw-bike-sharing
  MODEL_VERSION: "6"
