defaults:
  - dataset: kaggle
  - features: default
  - model: lgbm
  - simulation: default
  - paths: default
  - monitoring: default
  - training: default
  - validation: default
  - _self_

project: bike-sharing-forecast